### ISSUE TITLE
关于 ETL 的几点建议

### ISSUE THREAD

**Issue by beginor** [dotnetcore/SmartCode#44]
经过几小时的努力， 终于可以让 SmartCode 的 ETL 运行起来了， 自动生成数据库定义和迁移配置，只要再手工检查和修改少量配置就可以直接运使用了， 当然这个是不可避免的。 

有几点小小的建议， 希望能够采纳：

- 建议将 `ETLTaskRepository` 的连接串添加到 yml 配置， 现在要修改 `appsettings.json` ， 这个可以算是坑了；
- 建议将 `LoadBuildTask` 的 `PreCommand` 和 `PostCommand` 改成数组， 参考 DataX 的 `PreCommand` 和 `PostCommand` 设置， 一个字符串写太长还是比较别扭的， 改一下更好；
- 建议为 `LoadBuildTask` 增加一个一次插入多少行的配置， 分多次插入目标数据库， 现在应该是一次性全部插入目标数据库；

另外， ETL yml 配置中的全局参数必须有一个 `ETLTaskId` 配置， 否则就直接抛异常退出， 搜索 SmartCode 的代码， 也不知道是做什么用的， 而且没有相关说明， 默认也没有生成这个配置。

```yml
Parameters:
  ETLTaskId: 1
  ETLCode: Mssql2PG.Info_Item
  ETLRepository: PG
```
