### ISSUE TITLE
全大写数据库名称转换问题

### ISSUE THREAD

**Issue by NorthAlan** [dotnetcore/SmartCode#51]
SmartCode生成代码的时候，由于我们数据库的字段都是大写。
所以生成出来的字段名称变成了类似下面这个样：
有没有什么办法可以设置，名字是驼峰的~
`<ResultMap Id="ShippingOrderResultMap">`
`<Result Column="WH_ID" Property="WHID" />`
`<Result Column="SHIPPING_ORDER_ID" Property="SHIPPINGORDERID" />`
`<Result Column="OWNER_ID" Property="OWNERID" />`
`<Result Column="ORDER_STATUS_SC" Property="ORDERSTATUSSC" />`

数据库命名规范：单词大写+下划线

期望输出：转化之后的映射字段命名是 类似：OwnerId 而非 OWNERID。

**Comment by Ahoo-Wang** [comment]
![image](https://user-images.githubusercontent.com/4384159/77992085-ef28d100-7357-11ea-888a-36d1b0d7aa46.png)

相应配置节点下，参考以下配置
``` yml
NamingConverter:
  Column:
    Tokenizer:
      Type: Default
      Parameters:
        Delimiter: '_'
        UppercaseSplit: false #关闭大写分割
    Converter:
      Type: Pascal
```
